import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const TZ="Asia/Jakarta";
function normalizeUserDateTypos(text:string):string{
  return String(text||"").replace(/\b(\d{1,2})\s+(september|oktober|november|desember|januari|februari|maret|april|mei|juni|juli|agustus)\s+20206\b/gi,"$1 $2 2026");
}
function isoDateOnly(v:unknown):string|null{if(!v)return null;const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(s);if(Number.isNaN(d.getTime()))return null;return new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(d);}
function addDays(date:string,n:number){const d=new Date(date+"T00:00:00+07:00");d.setDate(d.getDate()+n);return new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(d);}
async function callTikTok(action:string,payload:Record<string,unknown>){const base=Deno.env.get("SUPABASE_URL"),key=Deno.env.get(["SUPABASE","SERVICE","ROLE","KEY"].join("_"));if(!base||!key)throw new Error("backend_configuration_incomplete");const r=await fetch(base+"/functions/v1/tiktok-api",{method:"POST",headers:{"content-type":"application/json","apikey":key,"authorization":"Bearer "+key},body:JSON.stringify({action,...payload})});const data=await r.json().catch(()=>null);if(!r.ok||!data?.ok){const detail=data?.data?.message||data?.data?.error?.message||data?.data?.code||data?.error||data?.message||"tiktok_api_error";throw new Error("tiktok_api_error:"+String(detail).slice(0,300));}return data;}
function isFinanceQuestion(text:string):boolean{const s=String(text||"").toLowerCase();return /\b(uang|cair|settlement|fee|netto|bersih|pajak|profit|margin|earning|revenue|payout|tarik|deposit|balance|hutang|finansial|keuangan|pendapatan)\b/i.test(s);}
async function handleFinanceQuestion(userMessage:string,chatId:string,requestId:string,workingContext:any,runTool:any,contextFromTool:any,saveConversation:any,logHermesToolRun:any){console.log(`[HERMES] Finance question detected: "${userMessage}"`);try{const date=isoDateOnly(new Date());console.log(`[HERMES] Calling finance_summary tool with date=${date}`);const toolResult=await runTool("finance_summary",{date});console.log(`[HERMES] finance_summary tool result received`);const lastTool="finance_summary";const lastIntent="finance_question";const updatedContext={...workingContext,...contextFromTool("finance_summary",{date},toolResult)};await logHermesToolRun(chatId,requestId,"finance_question","finance_summary","tiktok_api",{date},toolResult,"success");const data=toolResult?.data||{};const fmtRp=(n:any)=>{const num=Math.round(Number(n)||0);return"Rp "+num.toLocaleString("id-ID");};console.log(`[HERMES] Parsing data: three_components=${JSON.stringify(data.three_components)}`);const threeComp=data.three_components||{yang_bisa_dicairkan:0,yang_belum_bisa_dicairkan:0,yang_sudah_dicairkan:0};const yBisaDicairkan=Number(threeComp.yang_bisa_dicairkan)||0;const yBelumDicairkan=Number(threeComp.yang_belum_bisa_dicairkan)||0;const ySudahDicairkan=Number(threeComp.yang_sudah_dicairkan)||0;const totalNetIncome=yBisaDicairkan+yBelumDicairkan;const statements=data.statements||{total_amount:0,count:0};const withdrawals=data.withdrawals||{total_amount:0,count:0};const unsettled=data.unsettled||{total_amount:0,count:0};const answer=`💰 **LAPORAN KEUANGAN TIKTOK SHOP**\n\nPeriode: ${date} WIB\n\n📊 **RINGKASAN PENDAPATAN BERSIH** [1]\n├─ Selesai (Settlement): ${fmtRp(yBisaDicairkan)}\n├─ Untuk Dibayar (In Transit): ${fmtRp(yBelumDicairkan)}\n└─ **Total Pendapatan Bersih: ${fmtRp(totalNetIncome)}**\n\n---\n\n✅ **SETTLEMENT SELESAI**\nTotal: ${fmtRp(yBisaDicairkan)} (${statements.count||0} transaksi)\n\n---\n\n💳 **DANA SUDAH DICAIRKAN (Withdrawn)**\nTotal: ${fmtRp(ySudahDicairkan)} (${withdrawals.count||0} transaksi)\n\n---\n\n⏳ **DANA DALAM PROSES (Belum Dicairkan)**\nTotal: ${fmtRp(yBelumDicairkan)} (${unsettled.count||0} transaksi)\nStatus: Menunggu transfer ke rekening bank atau paket diterima pembeli.\n\n---\n\n📝 **Catatan:**\nPendapatan Bersih = Selesai + Untuk Dibayar [1]`;if(chatId){await saveConversation(chatId,userMessage,answer,updatedContext,lastTool,lastIntent);}return{ok:true,request_id:requestId,answer};}catch(e){console.error("[HERMES] Error on finance_summary tool:",e);return{ok:false,error:String(e),answer:"Maaf, gagal mengambil data keuangan live dari TikTok API. Saya tidak akan mengarang data.",request_id:requestId};}}
async function runTool(name:string,args:any){if(name==="finance_summary"){const date=isoDateOnly(args?.date);let start=isoDateOnly(args?.start_date),end=isoDateOnly(args?.end_date);if(date){start=date;end=date;}if(!end){end=isoDateOnly(new Date())!;}if(!start){start=addDays(end,-6);}console.log(`[HERMES-FINANCE-SUMMARY] Calling tiktok-api with start_date=${start}, end_date=${end}`);const result=await callTikTok("finance_overview",{start_date:start,end_date:end});console.log(`[HERMES-FINANCE-SUMMARY] TikTok API response received`);if(result?.period){result.period.timezone=TZ;}return result;}throw new Error("unsupported_tool");}
async function logHermesToolRun(chatId:string,requestId:string,intent:string,toolName:string,sourceName:string,args:any,result:any,status:string,errorMessage:string|null=null){const base=Deno.env.get("SUPABASE_URL"),key=Deno.env.get(["SUPABASE","SERVICE","ROLE","KEY"].join("_"));if(!base||!key)return;try{await fetch(base+"/rest/v1/rpc/hermes_log_tool_run",{method:"POST",headers:{apikey:key,authorization:"Bearer "+key,"content-type":"application/json"},body:JSON.stringify({p_chat_id:chatId||null,p_request_id:requestId,p_intent:intent||null,p_tool_name:toolName,p_source_name:sourceName||null,p_parameters:args||{},p_result_summary:result?.summary||result?.data?.summary||{},p_row_count:Array.isArray(result?.data?.orders)?result.data.orders.length:(Array.isArray(result?.orders)?result.orders.length:null),p_status:status,p_error_message:errorMessage,p_started_at:new Date().toISOString(),p_finished_at:new Date().toISOString(),p_latency_ms:null})})}catch(e){console.error("HERMES_TOOL_LOG_ERROR",String(e))}}
async function saveConversation(chatId:string,userText:string,assistantText:string,context:any,lastTool:string|null,lastIntent:string|null){const base=Deno.env.get("SUPABASE_URL"),key=Deno.env.get(["SUPABASE","SERVICE","ROLE","KEY"].join("_"));if(!base||!key||!chatId)return;try{const headers={apikey:key,authorization:"Bearer "+key,"content-type":"application/json"};await fetch(base+"/rest/v1/hermes_conversations",{method:"POST",headers:{...headers,"prefer":"resolution=merge-duplicates"},body:JSON.stringify({chat_id:chatId,updated_at:new Date().toISOString(),context:context||{},last_tool:lastTool,last_user_intent:lastIntent})});await fetch(base+"/rest/v1/hermes_messages",{method:"POST",headers:{...headers,"prefer":"return=minimal"},body:JSON.stringify([{chat_id:chatId,role:"user",content:userText},{chat_id:chatId,role:"assistant",content:assistantText}])});}catch(e){console.error("HERMES_MEMORY_SAVE_ERROR",String(e));}}
function contextFromTool(name:string,args:any,result:any){const c:any={last_tool:name};if(args?.date)c.date=args.date;if(result?.period)c.period=result.period;return c;}
Deno.serve(async req=>{const requestId=crypto.randomUUID();if(req.method!=="POST")return json({ok:false,error:"method_not_allowed",request_id:requestId},405);try{const body=await req.json().catch(()=>({})),rawUserMessage=String(body?.message||body?.user_message||"").trim(),userMessage=normalizeUserDateTypos(rawUserMessage),chatId=String(body?.chat_id||"").trim();if(!userMessage)return json({ok:false,error:"message_required",request_id:requestId},400);let workingContext:any={};if(isFinanceQuestion(userMessage)){const result=await handleFinanceQuestion(userMessage,chatId,requestId,workingContext,runTool,contextFromTool,saveConversation,logHermesToolRun);return json(result,result.ok?200:500);}return json({ok:false,error:"non_finance_question",request_id:requestId},400);}catch(e){const err=String(e instanceof Error?e.message:"internal_error");console.error("HERMES_REQUEST_ERROR",JSON.stringify({request_id:requestId,error:err}));return json({ok:false,error:err,answer:"Hermes mengalami kendala.",request_id:requestId},500);}});
